services:
  - type: web
    name: kashmakr-gig-3b6d2e61-t1278
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
